# This is the default configuration file of BungeeTabListPlus.
#
# Since the configuration of the plugin is quite complex you
# might want to have a look at the wiki from time to time.
#
# Wiki: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki
#  Placeholders: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Placeholders
#  Examples: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples
#

# Configure who can see the tab lists
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/MultipleTablists
showTo: "all"
priority: 0

# Configure header and footer
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-3---Header-and-Footer
showHeaderFooter: true
header:
  - "&cWelcome &f${viewer name}"
  - "&eW&celcome &f${viewer name}"
  - "&eWe&clcome &f${viewer name}"
  - "&eWel&ccome &f${viewer name}"
  - "&eWelc&come &f${viewer name}"
  - "&eWelco&cme &f${viewer name}"
  - "&eWelcom&ce &f${viewer name}"
  - "&eWelcome &f${viewer name}"
  - "&cW&eelcome &f${viewer name}"
  - "&cWe&elcome &f${viewer name}"
  - "&cWel&ecome &f${viewer name}"
  - "&cWelc&eome &f${viewer name}"
  - "&cWelco&eme &f${viewer name}"
  - "&cWelcom&ee &f${viewer name}"
  - "&cWelcome &f${viewer name}"
headerAnimationUpdateInterval: 0.2
footer:
  - |-
   &4Minecraft Middle Earth&7 https://www.mcmiddleearth.com/
   You are connected to ${viewer server} and within world ${viewer world}
footerAnimationUpdateInterval: 5

# Custom placeholders are a powerful mechanism to add more dynamic content
# to the tab list.
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/CustomPlaceholders
customPlaceholders:
  # Defines the ${afk_tag} placeholder which is used to add "|away"
  # to the players name if he is afk.
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: "&7|&oaway"
    false: ""
  # Defines the ${viewer_colored_ping} placeholder which adds a color code to
  # the ping using the following color scheme:
  # 0 - 49   -> green
  # 50 - 149 -> yellow
  # 150+     -> red
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"

# Player sets are required to display players and player counts on the tab list.
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-4---Player-sets
playerSets:
  all_players:
    filter: true
  same_server:
    filter: ${player server} == ${viewer server}

# Type of the tab list
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-5---Dynamic-Size-Tablist
# and https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-6---Fixed-Size-Tablist-Introduction
# for different options
type: FIXED_SIZE
size: 80

defaultIcon: colors/dark_gray.png
defaultPing: 1000

# Here the content of the tab list is configured:
components:
  - {text: "&cConnected: &6${viewer server}", icon: "default/server.png", ping: 0}
  - {text: "&cRank: &6${viewer vault_prefix}", icon: "default/rank.png", ping: 0}
  - {text: "&cPing: ${viewer_colored_ping}ms", icon: "default/ping.png", ping: 0}
  - {text: "&cServer: ${viewer server tps} tps", icon: "default/ping.png", ping: 0}
  - !players_by_server
    playerSet: all_players
    serverHeader:
    - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "default/server.png", ping: 0}
    serverSeparator:
    - {text: "", icon: "colors/red.png", ping: 0}
    -
    -
    showServers: ONLINE
# playerComponent: "${player vault_prefix} ${player name}${afk_tag}"
    playerComponent: "${player mcmeChat_moderator_prefix} ${player mcmeChat_color}${player name}${player mcmeChat_badge_suffix}${afk_tag}"
    morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
  - !spacer {}
  - {text: "&cTime: &6${time H:mm:ss}", icon: "default/clock.png", ping: 0}
  - {text: "&cPlayers: &6${playerset:all_players size}", icon: "default/players.png", ping: 0}
  - {text: "&cBalance: &6${viewer vault_balance 1.2}", icon: "default/balance.png", ping: 0}
  - {text: "", ping: 0}
