name: ${project.artifactId}
main: com.mcmiddleearth.mcmechat.ChatPlugin
version: ${project.version}
author: Eriol_Eandur
softdepend: [Tab]
depend: [Essentials, LuckPerms, PlaceholderAPI]

commands:
   mcmechat:
      description: reloads config file
      usage: /mcmechat reload

